courses/urls.py
from django.conf.urls import url

from . import views
app_name = 'courses'
urlpatterns = [
    url(r'^(?P<course_id>[0-9]+)/$', views.course_item, name='detail'),
]

polls/urls.py
from django.conf.urls import url

from . import views


app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='polls_index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='polls_detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='polls_results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='polls_vote'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^quadratic/', include('quadratic.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^student_list/$', views.student_list, name='student_list'),
    url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^courses/', include('courses.urls')),
    url(r'^students/', include('students.urls')),
]

students/urls.py
from django.conf.urls import url
from students.views import students, student

app_name = 'students'
urlpatterns = [
    url(r'^$', students, name='students'),
    url(r'^(?P<student_id>[0-9]+)/$', student, name='student'),
]

students/models.py
from django.db import models
from courses.models import Course


# Create your models here
class Students(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    email = models.EmailField()
    phone = models.CharField(max_length=13)
    address = models.CharField(max_length=200)
    skype = models.CharField(max_length=100)
    courses = models.ManyToManyField(Course)

    def __str__(self):
        return self.name + ' ' + self.surname

students/forms.py
from django import forms
from .models import Student


class StudentModelForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'surname', 'date_of_birth', 'email', 'phone', 'address', 'skype', 'courses']

students/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from .models import Student
from .forms import StudentModelForm
from courses.models import Course
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

import logging
logger = logging.getLogger(__name__)


class StudentListView(ListView):
    model = Student
    paginate_by = 2

    def get_queryset(self, page):
        queryset = super().get_queryset()
        course_id = self.request.GET.get('course_id', None)
        if course_id:
            queryset = Student.objects.filter(courses__id=course_id)
        return queryset


class StudentDetailView(DetailView):

    logger.debug('Students detail view has been debugged!')
    logger.warning('Logger of students detail view warns you!')
    logger.info('Logger of students detail view informs you!')
    logger.error('Students detail view went wrong!')

    model = Student


class StudentCreateView(CreateView):
    model = Student
    success_url = reverse_lazy('students:list_view')
    form_class = StudentModelForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Student registration'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(
            self.request,
            'Student {} {} has been successfully added.'.format(self.object.name, self.object.surname)
        )

        return response


class StudentUpdateView(UpdateView):
    model = Student
    success_url = reverse_lazy('students:list_view')
    form_class = StudentModelForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Student info update'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(
            self.request,
            'Info on the student has been successfully changed.'
        )

        return response


class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('students:list_view')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Student info suppression'
        return context

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(
            self.request,
            'Student {} {} has been successfully deleted.'.format(self.object.name, self.object.surname)
        )

        return response

students/templates/students/detail.html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mother of all Bursas, father of all Python">
    <meta name="author" content="Kostyantyn Kedrya">
    <title>The PythoThrone - main page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div class="container">
    <div class="header clearfix main-header">
        <!-- The nav section -->
        <nav>
            <ul class="nav nav-pills float-right">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'index' %}">Main</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'students:students' %}">Students</a>
                </li>
            </ul>
        </nav>
        <h3 class="project-title">The PythonThrone</h3>
    </div>
    <!-- End of nav section -->

    <h1>{{ student|stringformat:"s" }}</h1>
    <table>
        <tbody>
        <tr>
            <td>
                дата рождения
            </td>
            <td>
                {{ student.date_of_birth }}
            </td>
        </tr>
        <tr>
            <td>адрес</td>
            <td>{{ student.address }}</td>
        </tr>
        <tr>
            <td>почта</td>
            <td>{{ student.email }}</td>
        </tr>
        <tr>
            <td>логин skype</td>
            <td>{{ student.skype }}</td>
        </tr>
        <tr>
            <td>телефон</td>
            <td>{{ student.phone }}</td>
        </tr>
        <tr>
            <td>курсы</td>
            <td>
                <ul>
                    {% for course in student.courses.all %}
                        <li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<!-- Footer section -->
<footer class="main-footer">
    <p class="text-center">&copy; The PythonThrone 2017, all rights reserved</p>
</footer>
</div> <!-- /container -->
<!-- The js block -->
<script type="text/javascript" src="../static/js/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="../static/js/bootstrap.js"></script>
<!-- End of js block -->
</body>

students/templates/students/list_view.html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mother of all Bursas, father of all Python">
    <meta name="author" content="Kostyantyn Kedrya">
    <title>The PythoThrone - main page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<div class="container">
    <div class="header clearfix main-header">
        <!-- The nav section -->
        <nav>
            <ul class="nav nav-pills float-right">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'index' %}">Main</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'students:students' %}">Students</a>
                </li>
            </ul>
        </nav>
        <h3 class="project-title">The PythonThrone</h3>
    </div>
    <!-- End of nav section -->
<h1>Список студентов</h1>
    <table>
        <tbody>
        <tr>
            <th>#</th>
            <th>фамилия имя</th>
            <th>адрес</th>
            <th>skype</th>
            <th>курсы</th>
        </tr>
        {% for student in students %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'students:student' student.id %}">{{ student|stringformat:"s" }}</a></td>
                <td>{{ student.address }}</td>
                <td>{{ student.skype }}</td>
                <td>
                    <ul>
                        {% for course in student.courses.all %}
                            <li><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<!-- Footer section -->
<footer class="main-footer">
    <p class="text-center">&copy; The PythonThrone 2017, all rights reserved</p>
</footer>
</div> <!-- /container -->
<!-- The js block -->
<script type="text/javascript" src="../static/js/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="../static/js/bootstrap.js"></script>
<!-- End of js block -->
</body>