coaches/urls.py
from django.conf.urls import url

from . import views

app_name = 'coaches'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail')
]

courses/urls.py
from django.conf.urls import url

from . import views
app_name = 'courses'
urlpatterns = [
    url(r'^(?P<course_id>[0-9]+)/$', views.course_item, name='detail'),
]

feedbacks/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.FeedbackView.as_view(), name='feedback'),
]

polls/urls.py
from django.conf.urls import url

from . import views


app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='polls_index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='polls_detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='polls_results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='polls_vote'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^quadratic/', include('quadratic.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^student_list/$', views.student_list, name='student_list'),
    url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^courses/', include('courses.urls')),
    url(r'^students/', include('students.urls')),
]

students/urls.py
from django.conf.urls import url
from students.views import students, student

app_name = 'students'
urlpatterns = [
    url(r'^$', students, name='students'),
    url(r'^(?P<student_id>[0-9]+)/$', student, name='student'),
]

courses/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=100)
    short_description = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    subject = models.CharField(max_length=200)
    description = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    def __str__(self):
        return self.subject

feedbacks/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Feedback(models.Model):
    name = models.CharField(max_length=200)
    subject = models.CharField(max_length=200)
    message = models.TextField()
    from_email = models.EmailField()
    create_date = models.DateTimeField(auto_now_add=True)

feedbacks/forms.py
from django import forms
from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'subject', 'message', 'from_email']

feedbacks/views.py
from .models import Feedback
from .forms import FeedbackForm
from django.views.generic.edit import CreateView
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.mail import mail_admins


class FeedbackView(CreateView):
    model = Feedback
    form_class = FeedbackForm
    template_name = 'feedback.html'
    success_url = reverse_lazy('feedback')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(
            self.request,
            'Thank you for your feedback! We will keep in touch with you very soon!'
        )
        mail_admins(self.object.subject,
                    self.object.message)

        return response

templates/add_lesson.html
{% extends 'base.html' %}

{% block title%}Add new lesson{% endblock %}


{% block active_main_class %}class="active"{% endblock %}


{% block content %}
<h2>Add new lesson</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Slava NIk">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>
  <body>
  	<div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item">
              <a class="nav-link {% block nav_index %}{% endblock nav_index %}" href="{% url 'index' %}">
                  Main
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% block nav_contact %}{% endblock nav_contact %}" href="{% url 'contact' %}">
                  Contacts
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% block nav_students %}{% endblock nav_students %}" href="{% url 'students:index' %}">
                  Students
              </a>
            </li>
          </ul>
        </nav>
      </div>
      {% block main_content %}{% endblock main_content %}
    <footer class="text-muted">
      <p class="text-center">&copy; The PySchool 2017, some rights reserved</p>
    </footer>
  </div>
  <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  </body>

templates/coach_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Coach Details | {{ coach.first_name }} {{ coach.last_name }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="bursa-navbar">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">Main</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'contact' %}">Contacts</a></li>
                    <li><a class="nav-link" href="{% url 'students:list_view' %}?course_id={{ course.id }}">Students</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<div class="container">
    <h1>{{ coach.first_name }} {{ coach.last_name }}</h1>
    <table>
        <tbody>
        <tr>
            <td>дата рождения</td>
            <td>{{ coach.date_of_birth }}</td>
        </tr>
        <tr>
            <td>адрес</td>
            <td>{{ coach.address }}</td>
        </tr>
        <tr>
            <td>почта</td>
            <td>{{ coach.email }}</td>
        </tr>
        <tr>
            <td>логин skype</td>
            <td>{{ coach.skype }}</td>
        </tr>
        <tr>
            <td>телефон</td>
            <td>{{ coach.phone }}</td>
        </tr>
        {% if coach_courses %}
        <tr>
            <td>курсы учитель</td>
            <td>
                {% for course in coach_courses %}
                <p>
                    <a href="{% url 'courses:detail' course_id=course.id %}">{{ course.name }}</a>
                    студенты курса
                    <a href="{% url 'students:list_view' %}?course_id={{ course.id }}">
                        <span class="glyphicon glyphicon-new-window">туда</span>
                    </a>
                </p>
                {% endfor %}
            </td>
        </tr>
        {% endif %}
        {% if coach_assistant %}
        <tr>
            <td>курсы ассистент</td>
            <td>
                {% for course in coach_assistant %}
                <p>
                    <a href="{% url 'courses:detail' course_id=course.id %}">{{ course.name }}</a>
                    студенты курса
                    <a href="{% url 'students:list_view' %}?course_id={{ course.id }}">
                        <span class="glyphicon glyphicon-new-window">туда</span>
                    </a>
                </p>
                {% endfor %}
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
</body>
</html>

templates/contact.html
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mother of all Bursas, father of all Python">
    <meta name="author" content="Kostyantyn Kedrya">
    <title>The PythoThrone - contacts page</title>
    {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
      <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  </head>
  <body>
  	<div class="container">
      <div class="header clearfix main-header">
        <!-- The nav section -->
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Main</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'contact' %}">Contacts</a>
            </li>
			<li class="nav-item">
                <a class="nav-link" href="{% url 'students:students' %}">Students</a>
            </li>
          </ul>
        </nav>
        <h3 class="project-title">The PythonThrone</h3>
      </div>
      <!-- End of nav section -->
      <div class="row contacts">
        <div class="col-lg-12">
        <article class="main-content">
          <header>
            <h2>Contacts</h2>
          </header>

          <div class="row">
            <div class="col-lg-4">
              <div class="card contact-card" data-role="directore">
                <div class="card-body">
                  <h4 class="card-title director">Director</h4>
                  <p class="card-text name">Name: Peter Berg</p>
                  <p class="card-text skype">Skype: peter_berg</p>
                  <p class="card-text email">Email: p_berg@pythothrone.org</p>
                  <p class="card-text phone">Phone: +3812 255 55 56</p>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="card contact-card" data-role="manager">
                <div class="card-body">
                  <h4 class="card-title manager">Manager</h4>
                  <p class="card-text name">Name: Vanessa Lone</p>
                  <p class="card-text skype">Skype: vanessa_lone</p>
                  <p class="card-text email">Email: v_lone@pythothrone.org</p>
                  <p class="card-text phone">Phone: +3812 255 85 56</p>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="card contact-card" data-role="founde">
                <div class="card-body">
                  <h4 class="card-title founder">Founder</h4>
                  <p class="card-text name">Name: Cory North</p>
                  <p class="card-text skype">Skype: cory_north</p>
                  <p class="card-text email">Email: c_north@pythothrone.org</p>
                  <p class="card-tex phone">Phone: +3812 255 50 30</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        </article>
      </div><!-- /contacts -->
      <!-- Footer section -->
       <footer class="main-footer">
        <p class="text-center">&copy; The PythonThrone 2017, all rights reserved</p>
      </footer>
    </div> <!-- /container -->
    <!-- The js block -->
    <script type="text/javascript" src="../static/js/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <!-- End of js block -->
  </body>
</html>

templates/course_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Course Details | {{ course.name }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="bursa-navbar">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">Main</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'contact' %}">Contacts</a></li>
                    <li><a class="nav-link" href="{% url 'students:list_view' %}?course_id={{ course.id }}">Students</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

<div class="container index-container">
    <div id="course-information-block">
        <h1>{{ course.name }}</h1>
        <p>{{ course.description }}</p>
    </div>
    <div id="couses-wrapper">
        {% if course.coach or course.assistant %}
        <div>
            <h3>Преподаватели</h3>
            {% if course.coach %}
            <table>
                <tr>
                    <th>Учитель</th>
                </tr>
                <tr>
                    <td>
                        <a href="{% url 'coaches:detail' coach_id=course.coach.id %}">{{ course.coach.first_name }}
                            {{ course.coach.last_name }}</a></td>
                </tr>
                <tr>
                    <td>{{ course.coach.description }}</td>
                </tr>
            </table>
            {% endif %}
            {% if course.assistant %}
            <table>
                <tr>
                    <th>Учитель</th>
                </tr>
                <tr>
                    <td>
                        <a href="{% url 'coaches:detail' coach_id=course.assistant.id %}">{{ course.assistant.first_name }}
                            {{course.assistant.last_name }}</a></td>
                </tr>
                <tr>
                    <td>{{ course.assistant.description }}</td>
                </tr>
            </table>
            {% endif %}
        </div>
        <br/>
        {% endif %}
        <h3 id="program-header">План курса</h3>
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Тема</th>
                <th>Описание</th>
            </tr>
            </thead>
            <tbody>
            {% for lesson in course.lesson_set.all %}
            <tr>
                <td>{{ lesson.order }}</td>
                <td>{{ lesson.subject }}</td>
                <td>{{ lesson.description }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</body>
</html>

templates/feedback.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}Feedback{% endblock title %}

{% block feedback-active %}active{% endblock %}

{% block content %}
<h2>Feedback</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-default" value="Отправить">
</form>
{% endblock content %}

templates/inc_instructor.html
<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">{{ block_title }}</h3>
    </div>
    <div class="panel-body">
        <a href="{% url 'coaches:detail' instructor.id %}">{{ instructor.user.first_name }}
            {{ instructor.user.last_name }}</a>
        <p>{{ instructor.description }}</p>
    </div>
</div>

templates/index.html
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mother of all Bursas, father of all Python">
    <meta name="author" content="Kostyantyn Kedrya">
    <title>The PythoThrone - main page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
  	<div class="container">
      <div class="header clearfix main-header">
        <!-- The nav section -->
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'index' %}">Main</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contacts</a>
            </li>
			<li class="nav-item">
                <a class="nav-link" href="{% url 'students:students' %}">Students</a>
            </li>
          </ul>
        </nav>
        <h3 class="project-title">The PythonThrone</h3>
      </div>
      <!-- End of nav section -->
      <h1 class="display-3 course-name">Entering Django Bursa </h1>
      <h3 class="display-3 course-description">Description</h3>
      <div class="jumbotron curse-promo">
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <div class="btn btn-lg btn-success" role="button">Enrole the course</div>
      </div><!-- /jumbotron -->
      <div class="row about-course">
          <div class="col-lg-12">
          <table>
              <tr>
                  <th>Курс</th>
                  <th>Описание</th>
              </tr>
              {% for course in courses %}
                  <tr>
                      <td><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></td>
                      <td>{{ course.short_description }}</td>
                  </tr>
              {% endfor %}
          </table>
          </div>
      </div>
      <!-- Footer section -->
       <footer class="main-footer">
        <p class="text-center">&copy; The PythonThrone 2017, all rights reserved</p>
      </footer>
    </div> <!-- /container -->
    <!-- The js block -->
    <script type="text/javascript" src="../static/js/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <!-- End of js block -->
  </body>

templates/student_detail.html
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mother of all Bursas, father of all Python">
    <meta name="author" content="Kostyantyn Kedrya">
    <title>The PythoThrone - Artem Tarasov summery</title>
    {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
      <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  </head>
  <body>
  	<div class="container">
      <div class="header clearfix main-header">
        <!-- The nav section -->
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Main</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contacts</a>
            </li>
			      <li class="nav-item">
                      <a class="nav-link" href="{% url 'students:students' %}">Students</a>
            </li>
          </ul>
        </nav>
        <h3 class="project-title">The PythonThrone</h3>
      </div>
      <!-- End of nav section -->
      <div class="main-content">
        <h1 class="display-3 student-name">Tarasov Artem</h1>
		    <section class="student-summery">
		    <table class="table table-striped">
        	<tbody>
        		<tr>
        			<td>
                Surname
        			</td>
        			<td>
        				Tarasov
        			</td>
            </tr>
            <tr>
              <td>
                Name
              </td>
              <td>
                Artem
              </td>
            </tr>
            <tr>
              <td>
        				Patronymic
        			</td>
              <td>
                Ivanovich
              </td>
            </tr>
            <tr>
              <td>
                Birth Date
              </td>
              <td>
                20/10/1995
              </td>
            </tr>
             <tr>
               <td>
         			Average Grade
         			</td>
               <td>
         				100
         			</td>
         		</tr>
            <tr>
              <td>
        				Rating
        			</td>
              <td>
        				3
        			</td>
        		</tr>
            <tr>
              <td>
                Address
              </td>
              <td>
                ул. Каразина, 2, г. Харьков, Украина
              </td>
            </tr>
            <tr>
              <td>
        				E-mail
        			</td>
              <td>
        				artem.tarasov@nixsolutions.com
        			</td>
        		</tr>
        		<tr>
              <td>
        				Skype
        			</td>
              <td>
        				tematarasow
        			</td>
        		</tr>
        	</tbody>
        </table>
        </section>
        <section class="course-summery">
          <table class="table table-inverse">
            <thead>
              <th>
                Course
              </th>
              <th>
                Week
              </th>
              <th>
                Control Type
              </th>
              <th>
                Grade
              </th>
            </thead>
            <tbody>
              <tr>
                <td rowspan="2">
                  PY01 Введение в Django
                </td>
                <td rowspan="2">
                  Week 1
                </td>
                <td>
                  Tests
                </td>
                <td>
                  100%
                </td>
              </tr>
              <tr>

                <td>
                  Problem Task №1
                </td>
                <td>
                  100%
                </td>
              </tr>
            </tbody>
          </table>
        </section>

      </div>
      <!-- Footer section -->
       <footer class="main-footer">
        <p class="text-center">&copy; The PythonThrone 2017, all rights reserved</p>
      </footer>
    </div> <!-- /container -->
    <!-- The js block -->
    <script type="text/javascript" src="../static/js/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <!-- End of js block -->
  </body>

templates/student_list.html
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Mother of all Bursas, father of all Python">
    <meta name="author" content="Kostyantyn Kedrya">
    <title>The PythoThrone - students list page</title>
    {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
      <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  </head>
  <body>
  	<div class="container">
      <div class="header clearfix main-header">
        <!-- The nav section -->
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Main</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contacts</a>
            </li>
			      <li class="nav-item">
                      <a class="nav-link" href="{% url 'students:students' %}">Students</a>
            </li>
          </ul>
        </nav>
        <h3 class="project-title">The PythonThrone</h3>
      </div>
      <!-- End of nav section -->
      <div class="main-content">
        <h1 class="display-3 course-name">Студенты курса Entering Django Bursa </h1>
		    <section class="Content description">
          <p>Ниже представлен список студентв, выпуска - сентябрь 2017</h3>
        <section/>
		    <table class="table table-striped">
        	<thead>
        		<tr>
        			<th>
        				No
        			</th>
        			<th>
        				Surname
        			</th>
        			<th>
        				Name
        			</th>
        			<th>
        				Address
        			</th>
        			<th>
        				Skype
        			</th>
        		</tr>
        	</thead>
        	<tbody>
        		<tr>
        			<td>
        				<a href="{% url 'student_detail' %}">1</a>
        			</td>
        			<td>
        				Tarasov
        			</td>
        			<td>
        				Artem
        			</td>
        			<td>
        				ул. Каразина, 2, г. Харьков, Украина
        			</td>
        			<td>
        				tematarasow
        			</td>
        		</tr>
        		<tr>
        			<td>
        				2
        			</td>
        			<td>
        				Voskresenskyi
        			</td>
        			<td>
        				Vadym
        			</td>
        			<td>
        			   ул. Каразина, 2, г. Харьков, Украина
        			</td>
        			<td>
        				voskresvadim
        			</td>
        		</tr>
        		<tr>
        			<td>
        				3
        			</td>
        			<td>
        				Arhipov
        			</td>
        			<td>
        			   Vladislav
        			</td>
        			<td>
        				ул. Каразина, 2, г. Харьков, Украина
        			</td>
        			<td>
        				vladislav.arhipov89
        			</td>
        		</tr>
        		<tr>
        			<td>
        				4
        			</td>
        			<td>
        				Kovalenko
        			</td>
        			<td>
        				Viacheslav
        			</td>
        			<td>
        				ул. Каразина, 2, г. Харьков, Украина
        			</td>
        			<td>
        				mcamradm
        			</td>
        		</tr>
        		<tr>
        			<td>
        				5
        			</td>
        			<td>
        				Pavlenko
        			</td>
        			<td>
        				Alexander
        			</td>
        			<td>
        				ул. Каразина, 2, г. Харьков, Украина
        			</td>
        			<td>
                live:e1cfb12dcb9cd614
        			</td>
        		</tr>
            <tr>
        			<td>
        				6
        			</td>
        			<td>
        				Nikolaenko
        			</td>
        			<td>
        				Slava
        			</td>
        			<td>
        				ул. Каразина, 2, г. Харьков, Украина
        			</td>
        			<td>
        				slava_nikolaenko
        			</td>
        		</tr>
            <tr>
        			<td>
        				7
        			</td>
        			<td>
        			  Butko
        			</td>
        			<td>
        				Maksim
        			</td>
        			<td>
        				ул. Каразина, 2, г. Харьков, Украина
        			</td>
        			<td>
        				maksim.butkko
        			</td>
        		</tr>
            <tr>
        			<td>
        				8
        			</td>
        			<td>
        				Kedrya
        			</td>
        			<td>
        			  Constantin
        			</td>
        			<td>
        				ул. Каразина, 2, г. Харьков, Украина
        			</td>
        			<td>
        				konstantin.kedrya
        			</td>
        		</tr>
        	</tbody>
        </table>
      </div>
      <!-- Footer section -->
       <footer class="main-footer">
        <p class="text-center">&copy; The PythonThrone 2017, all rights reserved</p>
      </footer>
    </div> <!-- /container -->
    <!-- The js block -->
    <script type="text/javascript" src="../static/js/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/js/bootstrap.js"></script>
    <!-- End of js block -->
  </body>