courses/urls.py
from django.conf.urls import url

from . import views
app_name = 'courses'
urlpatterns = [
    url(r'^(?P<course_id>[0-9]+)/$', views.course_item, name='detail'),
]

polls/urls.py
from django.conf.urls import url

from . import views


app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='polls_index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='polls_detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='polls_results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='polls_vote'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^quadratic/', include('quadratic.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^student_list/$', views.student_list, name='student_list'),
    url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^courses/', include('courses.urls')),
    url(r'^students/', include('students.urls')),
]

courses/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=100)
    short_description = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    subject = models.CharField(max_length=200)
    description = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    def __str__(self):
        return self.subject

courses/forms.py
from django import forms
from .models import Course, Lesson


class CourseModelForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'short_description', 'description', 'coach', 'assistant']


class LessonModelForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['subject', 'description', 'course', 'order']

courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Course, Lesson
from .forms import CourseModelForm, LessonModelForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

import logging
logger = logging.getLogger(__name__)


class CourseDetailView(DetailView):

    logger.debug('Courses detail view has been debugged!')
    logger.warning('Logger of courses detail view warns you!')
    logger.info('Logger of courses detail view informs you!')
    logger.error('Courses detail view went wrong!')

    model = Course
    template_name = 'courses/detail.html'
    context_object_name = 'course'


class CourseCreateView(CreateView):
    model = Course
    template_name = 'courses/add.html'
    success_url = reverse_lazy('index')
    form_class = CourseModelForm

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Course ' + self.object.name + ' has been successfully added.')

        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Course creation'

        return context


class CourseUpdateView(UpdateView):
    model = Course
    form_class = CourseModelForm
    template_name = 'courses/edit.html'

    def get_success_url(self):
        return reverse_lazy('courses:edit', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'The changes have been saved.')

        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Course update'

        return context


class CourseDeleteView(DeleteView):
    model = Course
    template_name = 'courses/remove.html'
    form_class = CourseModelForm
    success_url = reverse_lazy('index')
    context_object_name = 'course'

    def delete(self, request, *args, **kwargs):
        response = super().delete(self, request, *args, **kwargs)
        messages.success(self.request, 'Course ' + self.object.name + ' has been deleted.')
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Course deletion'
        return context


def index(request):
    context = {'courses': Course.objects.all()}

    return render(request, 'index.html', context)


def detail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    lessons = Lesson.objects.filter(course__id__contains=course_id)
    context = {'course': course, 'lessons': lessons}

    return render(request, 'courses/detail.html', context)


def add(request):
    if request.method == 'POST':
        form = CourseModelForm(request.POST)
        course = form.save()
        messages.success(request, 'Course ' + course.name + ' has been successfully added.')
        return redirect('/')
    else:
        form = CourseModelForm()

    context = {'form': form}

    return render(request, 'courses/add.html', context)


def edit(request, course_id):
    course = get_object_or_404(Course, pk=course_id)

    if request.method == 'POST':
        form = CourseModelForm(request.POST, instance=course)
        form.save()
        messages.success(request, 'The changes have been saved.')

        return redirect('courses:edit', course_id=course.id)

    form = CourseModelForm(instance=course)
    context = {'form': form}

    return render(request, 'courses/edit.html', context)


def remove(request, course_id):
    course = get_object_or_404(Course, pk=course_id)

    if request.method == 'POST':
        course.delete()
        messages.success(request, 'Course ' + course.name + ' has been deleted.')

        return redirect('/')

    context = {'course': course}

    return render(request, 'courses/remove.html', context)


def add_lesson(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    if request.method == 'POST':
        form = LessonModelForm(request.POST)
        lesson = form.save()
        messages.success(request, 'Lesson ' + lesson.subject + ' has been successfully added.')
        return redirect('courses:detail', course_id=course.id)
    else:
        form = LessonModelForm(initial={'course': course})

    context = {'form': form}

    return render(request, 'courses/add_lesson.html', context)

templates/courses/add.html
{% extends 'base.html' %}

{% block title %} Add course {% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <h3>{{ title }}</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Создать">
        </form>
    </div>
</div>

{% endblock %}

templates/courses/add_lesson.html
{% extends 'base.html' %}


{% block title %}Create new lesson{% endblock %}


      {% block content %}
      <h1>Создание нового занятия</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Создать" />
      </form>
      {% endblock content %}

templates/courses/course.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Course</title>
    {% load static %}
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Project -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="{% static 'js/html5shiv.min.js' %}"></script>
        <script src="{% static 'js/respond.min.js' %}"></script>
      <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse bursaka-nav">
      <div class="container-fluid active">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'index' %}">Main</a></li>
            <li><a href="{% url 'contact' %}">Contacts</a></li>
            <li><a href="{% url 'student_list' %}">Students</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="bursaka-content">
      <div class="jumbotron matrix-theme">
        <div class="container">
          <div class="col-md-12">
            <div class="jumbotron">
              <h1 class="text-left text-uppercase bursaka-title-lg">{{ course.name }}</h1>
              <p class="description-content">{{ course.description }}</p>
              <h3>План курса:</h3>
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Тема</th>
                    <th>Описание</th>
                  </tr>
                </thead>
                <tbody>
                  {% for lesson in lesson_list %}
                    <tr>
                      <td>{{ lesson.id }}</td>
                      <td>{{ lesson.subject }}</td>
                      <td>{{ lesson.description }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer class="bursaka-footer"></footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/courses/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}The PySchool - {{ course.name }}{% endblock title %}
{% block description %}{{ course.description|truncatechars:32 }}{% endblock description %}
{% block main_content%}
  <h1 class="display-3 course-name">{{ course.name }} </h1>
  <div class="lead text-muted">
    <p>{{ course.description }}</p>
  </div>
  <h2>Преподаватели</h2>
{% include "includes/course_coach_include.html" with block_title="Учитель" instructor=course.coach %}
{% include "includes/course_coach_include.html" with block_title="Ассистент" instructor=course.assistant %}
  <div class="row about-course">
    <div class="col-lg-12">
      <article class="main-content">
        <h2>План курса</h2>
        <table class="table">
          <thead class="thead-inverse">
            <tr>
              <th>#</th>
              <th>Тема</th>
              <th>Описание</th>
            </tr>
          {% for lesson in lessons %}
            <tr>
              <td>{{ lesson.order }}</td>
              <td>{{ lesson.subject }}</td>
              <td>{{ lesson.description }}</td>
            </tr>
          {% endfor %}
          </thead>
        </table>
      </article>
    </div>
  </div>
{% endblock main_content %}

templates/courses/edit.html
{% extends 'base.html' %}

{% block title %} Edit course {% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <h3>{{ title }}</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Изменить">
        </form>
    </div>
</div>

{% endblock %}

templates/courses/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Main</title>
    {% load static %}
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Project -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="{% static 'js/html5shiv.min.js' %}"></script>
        <script src="{% static 'js/respond.min.js' %}"></script>
      <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse bursaka-nav">
      <div class="container-fluid active">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'courses:index' %}">Main</a></li>
            <li><a href="{% url 'contact' %}">Contacts</a></li>
            <li><a href="{% url 'students:list_view' %}">Students</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="bursaka-content">
      <div class="jumbotron matrix-theme">
        <div class="container">
          <div class="col-md-12">
            <div class="jumbotron">
              <h1 class="text-left text-uppercase bursaka-title-lg">Bursaka</h1>
              <p class="description-content">
                Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.
                Nam eget dui. Etiam rhoncus.
              </p>
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>КУрс</th>
                    <th>Описание</th>
                  </tr>
                </thead>
                <tbody>
                  {% for course in course_list %}
                    <tr>
                      <td><a href="{% url 'courses:courses' course.id %}">{{ course.name }}</a></td>
                      <td>{{ course.short_description }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer class="bursaka-footer"></footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/courses/list.html
{% extends 'index.html' %}
{% block title%}
  <title>Courses</title>
{% endblock %}

{% block links %}
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'courses:list_view' %}">Main</a><span class="sr-only">(current)</span></li>
        <li><a href="{% url 'contact' %}">Contacts</a></li>
        <li><a href="{% url 'students:list_view' %}">Students</a></li>
        <li><a href="{% url 'results' %}">Quadratic</a></li>
    </ul>
</div><!-- /.navbar-collapse -->
{% endblock %}

{% block content %}
<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><h2>Courses</h2></div>
    <div class="panel-body">
        <div class='otherContent'>list of courses</div>
    </div>
    <h2>Select a course</h2>
    <!-- Table -->
    <table class="table">
        <tr class='cust_div'>
            <th>Course</th>
            <th>Description</th>
        </tr>
        {% if courses_list %}
            {% for course in courses_list %}
            <tr>
                <td><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></td>
                <td>{{course.short_description}}</td>
            </tr>
            {% endfor %}
        {% else %}
        <p>No courses are available.</p>
        {% endif %}
    </table>
</div>
{% endblock %}

templates/courses/remove.html
{% extends 'base.html' %}

{% block students-active %} active {% endblock %}

{% block title %} Remove course {% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        <h3>{{ title }}</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            <p>Курс {{ course.name }} будет удален</p>
            <hr>
            <input class="btn btn-primary" type="submit" value="Удалить">
        </form>
    </div>
</div>

{% endblock %}