coaches/urls.py
from django.conf.urls import url

from . import views

app_name = 'coaches'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail')
]

courses/urls.py
from django.conf.urls import url

from . import views
app_name = 'courses'
urlpatterns = [
    url(r'^(?P<course_id>[0-9]+)/$', views.course_item, name='detail'),
]

polls/urls.py
from django.conf.urls import url

from . import views


app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='polls_index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='polls_detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='polls_results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='polls_vote'),
]

pybursa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^quadratic/', include('quadratic.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^student_list/$', views.student_list, name='student_list'),
    url(r'^student_detail/$', views.student_detail, name='student_detail'),
    url(r'^courses/', include('courses.urls')),
    url(r'^students/', include('students.urls')),
]

coaches/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Coach(models.Model):
    user = models.OneToOneField(get_user_model())
    date_of_birth = models.DateField()
    gender = models.CharField(choices=(
        ('M', 'Male'),
        ('F', 'Female')
    ), max_length=1)
    phone = models.CharField(max_length=25)
    address = models.CharField(max_length=255)
    skype = models.CharField(max_length=64)
    description = models.TextField()

    def __str__(self):
        return self.user.first_name

    @property
    def full_name(self):
        return self.user.first_name + ' ' + self.user.last_name

courses/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=100)
    short_description = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    subject = models.CharField(max_length=200)
    description = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    def __str__(self):
        return self.subject

coaches/views.py
from django.shortcuts import render, get_object_or_404
from .models import Coach


def detail(request, pk):
    coach = get_object_or_404(Coach, id=pk)
    return render(request, 'coaches/detail.html', {'coach': coach})

coaches/templates/coaches/detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Ooniversity{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Главная <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Контакты</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled"
                   href="{% url 'students:list_view' %}?course_id={{ course.id }}">Студенты</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-12">


            <h3>{{ coach.get_fool_name }}</h3>
            <hr>
            <p>дата рождения {{ coach.date_of_birth|date:"M d, Y" }}</p>
            <hr>
            <p>адрес {{ coach.address }}</p>
            <hr>
            <p>почта {{ coach.user.email }}</p>
            <hr>
            <p>логин skype {{ coach.skype }}</p>
            <hr>
            <p>телефон {{ coach.phone }}</p>
            <hr>

            <p>курсы учитель
                {% for course in coach.course_set.all %}
                    <a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a><br/>
                    <a class="nav-link"
                       href="{% url 'students:list_view' %}?course_id={{ course.id }}">Студенты</a>                {% endfor %}
                студенты курса

            </p>
            <hr>
            <p>курсы ассистент
                {% for course in coach.coach_assistant.all %}
                    <a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a><br/>
                    <a class="nav-link"
                       href="{% url 'students:list_view' %}?course_id={{ course.id }}">Студенты</a>
                {% endfor %}
                студенты курса </p>
            <hr>
        </div>
    </div>
</div>

<script src="{% static 'js/bootstrap.js' %}"></script>

</body>
</html>